const dressOptions = [
  {
    question: "What is your wedding theme?",
    options: [
      "Beach",
      "Rustic",
      "Classic",
      "Modern",
      "Bohemian",
      "Glamorous",
      "Vintage",
      "Urban",
      "Casual",
      "Traditional",
      "Winter",
      "Summer",
      "Destination",
      "Cultural",
      "Eco-Friendly",
    ],
  },
  {
    question: "What silhouette are you interested in?",
    options: [
      "A-line",
      "Ball Gown",
      "Mermaid",
      "Sheath",
      "Empire",
      "Fit and Flare",
      "Trumpet",
      "Column",
      "Tea-length",
      "Mini",
      "Peplum",
      "Drop Waist",
      "Layered",
      "Princess",
      "Asymmetrical",
    ],
  },
  {
    question: "Do you have any preferred fabric types?",
    options: [
      "Satin",
      "Lace",
      "Chiffon",
      "Tulle",
      "Organza",
      "Crepe",
      "Velvet",
      "Brocade",
      "Silk",
      "Georgette",
      "Mesh",
      "Flannel",
      "Jersey",
      "Leather",
      "Linen",
    ],
  },
  {
    question: "What type of neckline do you find most appealing?",
    options: [
      "Sweetheart",
      "V-neck",
      "Scoop",
      "Boat Neck",
      "High Neck",
      "Halter",
      "Off-the-Shoulder",
      "Square",
      "Cowl",
      "Jewel",
      "Keyhole",
      "Surplice",
      "Queen Anne",
      "Collared",
      "Plunge",
    ],
  },
  {
    question: "What sleeve style do you prefer for your dress?",
    options: [
      "Sleeveless",
      "Short Sleeves",
      "Long Sleeves",
      "Off-the-Shoulder",
      "Cap Sleeves",
      "Bell Sleeves",
      "Puff Sleeves",
      "Straight Sleeves",
      "Draped Sleeves",
      "Lace Sleeves",
    ],
  },
  {
    question: "Do you have any specific embellishments or decorations in mind?",
    options: [
      "Beads",
      "Sequins",
      "Pearls",
      "Embroidery",
      "Appliqué",
      "Lace",
      "Ruffles",
      "Bows",
      "Sashes",
      "Cut-outs",
      "Feathers",
      "Fringe",
      "Metallic Accents",
      "Rhinestones",
      "Studs",
    ],
  },
];

export default dressOptions;
